DROP TABLE IF EXISTS domains;

CREATE TABLE domains (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    domain TEXT NOT NULL,
    ip TEXT NOT NULL,
    password_hash TEXT NOT NULL
);
